export const restaurant = {
  name: 'UZKODA',
  tagline: 'Uzkodas · Banketi · Uzkodu piramīdas',
  description: 'Uzkodu piramīdas, banketi un pusdienotava. Sirsnīga ēdienreize jebkuram pasākumam.',
  highlight1: 'Tematiskie pasākumi · Banketu apkalpošana',
  highlight2: 'Sekojiet @uzkoda.info',
  phone: '__TODO_PHONE__',
  email: '',
  address: '__TODO_ADDRESS__',
  instagram: 'https://instagram.com/uzkoda.info',
  mapsLink: 'https://maps.google.com/?q=__TODO_ADDRESS__',
  hours: {
    weekday: 'Pirmdiena–Piektdiena: pēc pieprasījuma',
    friday: 'Sestdiena–Svētdiena: pasākumi un banketi',
    sunday: 'Sazinieties Instagram @uzkoda.info',
  },
  heroVideo: '/videos/hero.mp4',
  heroVideoStart: 0,
  aboutVideo: '/videos/foodpyramid.mp4',
  cinematicVideo: '/videos/themepartyvideo.mp4',
  colors: {
    primary: '#C9A84A',
    primaryDark: '#9B7E2C',
    bg: '#0E0B08',
    bgAlt: '#1A1410',
    text: '#F5EFE4',
    gray: '#9B8E7E',
  },
  menu: {
    Mains: [
      { name: 'Produkts 1', desc: '__TODO_PRODUCT_1_DESC__', price: '', img: '/menu/product1.jpg' },
      { name: 'Produkts 2', desc: '__TODO_PRODUCT_2_DESC__', price: '', img: '/menu/product2.jpg' },
      { name: 'Produkts 3', desc: '__TODO_PRODUCT_3_DESC__', price: '', img: '/menu/product3.jpg' },
    ],
  },
  menuImages: [
    '/menu/product1.jpg', '/menu/product2.jpg', '/menu/product3.jpg',
  ],
  reviews: [
    { stars: 5, text: 'Uzkodu piramīda mūsu kāzās bija īsts hits. Visi viesi bija sajūsmā!', name: 'Anna K.', time: '2 nedēļas atpakaļ', tags: ['Kāzas', 'Piramīda'] },
    { stars: 5, text: 'Pasūtījām banketu uzņēmuma pasākumam — viss bija perfekti.', name: 'Māris B.', time: '1 mēnesi atpakaļ', tags: ['Bankets', 'Korporatīvi'] },
    { stars: 5, text: 'Tematiskais ēdienu noformējums pārspēja visas cerības.', name: 'Ieva S.', time: '3 nedēļas atpakaļ', tags: ['Tematiski', 'Pasākums'] },
    { stars: 5, text: 'Garšīgi, skaisti, profesionāli. Iesaku no sirds.', name: 'Jānis R.', time: '1 nedēļa atpakaļ', tags: ['Kvalitāte', 'Apkalpošana'] },
    { stars: 5, text: 'Pusdienotavas ēdiens svaigs un mājīgs — atgriezīsimies.', name: 'Laura M.', time: '5 dienas atpakaļ', tags: ['Pusdienas', 'Regulāri'] },
    { stars: 5, text: 'Uzkodas izskatās un garšo lieliski. Paldies komandai!', name: 'Rihards T.', time: '4 nedēļas atpakaļ', tags: ['Uzkodas', 'Pasākums'] },
  ],
}
