export const restaurant = {
  name: 'Yerevan Pandok',
  tagline: 'Armēņu virtuve · Jūrmala',
  description: 'Autentiska armēņu ēdienkarte. Mājīga atmosfēra pie jūras.',
  highlight1: 'Konditoreja · +371 22300587',
  highlight2: 'Bērnu rotaļu istaba pieejama',
  phone: '+371 22308579',
  email: '',
  address: 'Jomas iela 25, Jūrmala, LV-2015',
  instagram: 'https://instagram.com/yerevan_pandok',
  mapsLink: 'https://maps.google.com/?q=Jomas+iela+25+Jurmala',
  hours: {
    weekday: 'Pirmdiena–Piektdiena: 12:00–22:00',
    friday: 'Sestdiena–Svētdiena: 12:00–22:00',
    sunday: 'Konditoreja: +371 22300587',
  },
  heroVideo: '/videos/hero.mp4',
  heroVideoStart: 4,
  aboutVideo: '/videos/interior.mp4',
  cinematicVideo: '/videos/hero.mp4',
  colors: {
    primary: '#6B3A2A',
    primaryDark: '#4A2418',
    bg: '#FDFAF5',
    bgAlt: '#F5EFE4',
    text: '#2C1810',
    gray: '#8C7B6B',
  },
  menu: {
    Starters: [
      { name: 'Hummus', desc: 'Armēņu klasika', price: '', img: '/images/menu-1.jpg' },
      { name: 'Dolma', desc: 'Vīnogu lapas ar gaļu', price: '', img: '/images/menu-2.jpg' },
      { name: 'Pita maize', desc: 'Svaigi cepta', price: '', img: '/images/menu-3.jpg' },
    ],
    Mains: [
      { name: 'Khorovats', desc: 'Armēņu šašliks', price: '', img: '/images/meat.jpg' },
      { name: 'Gvino', desc: 'Armēņu vīns', price: '', img: '/images/wine.jpg' },
      { name: 'Hačapuri', desc: 'Gruzīnu maizes klasika', price: '', img: '/images/hacapuri.jpg' },
    ],
    Bakery: [
      { name: 'Gata', desc: 'Armēņu konditorejas klasika', price: '', img: '/images/menu-7.jpg' },
      { name: 'Nazuk', desc: 'Sviesta cepumi', price: '', img: '/images/menu-8.jpg' },
      { name: 'Baklava', desc: 'Medus un riekstu kārtojums', price: '', img: '/images/menu-9.jpg' },
    ],
  },
  menuImages: [
    '/menu/1.jpg', '/menu/2.jpg', '/menu/3.jpg', '/menu/4.jpg',
    '/menu/5.jpg', '/menu/6.jpg', '/menu/7.jpg', '/menu/8.jpg',
    '/menu/9.jpg', '/menu/10.jpg', '/menu/11.jpg', '/menu/12.jpg',
    '/menu/13.jpg', '/menu/14.jpg',
  ],
  reviews: [
    { stars: 5, text: 'Labākais humuss Jūrmalā. Ģimenes atmosfēra un silta apkalpošana.', name: 'Anna K.', time: '1 nedēļa atpakaļ', tags: ['Humuss', 'Ģimene'] },
    { stars: 5, text: 'Bērnu istaba ir lieliska! Bērni priecīgi, vecāki var mierīgi ēst.', name: 'Māris B.', time: '2 nedēļas atpakaļ', tags: ['Bērni', 'Ģimene'] },
    { stars: 5, text: 'Khorovats ir fantastisks. Īstena armēņu garša Latvijā.', name: 'Ieva S.', time: '3 dienas atpakaļ', tags: ['Khorovats', 'Galvenie'] },
    { stars: 5, text: 'Konditoreja ir neticama. Baklava un gata — obligāti jāizmēģina.', name: 'Jānis R.', time: '1 mēnesi atpakaļ', tags: ['Konditoreja', 'Deserti'] },
    { stars: 5, text: 'Mājīga vieta ar lielisku ēdienu. Noteikti atgriezīsimies.', name: 'Laura M.', time: '5 dienas atpakaļ', tags: ['Atmosfēra', 'Regulāri'] },
    { stars: 5, text: 'Dolma un lavash maize bija izcila. Īsta armēņu virtuve.', name: 'Rihards T.', time: '2 nedēļas atpakaļ', tags: ['Dolma', 'Uzkodas'] },
  ],
}
